services:
  - type: web
    name: whatsapp-chatbot
    env: java
    plan: free
    region: singapore
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/WhatsappChatbotApplication-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 21